from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA_DIR = ROOT / "data"
LOG_DIR = ROOT / "logs"
DB_PATH = DATA_DIR / "synapse.db"

BACKEND_PORT = 3001
BRIDGE_PORT = 5002
FRONTEND_PORT = 8080

EMBED_DIM = 200

LOCAL_CONFIDENCE_THRESHOLD = 0.65
LOCAL_MIN_SCORE = 0.15

MAX_WEB_SOURCES = 3
MAX_SUMMARY_SENTENCES = 3
WEB_TIMEOUT_SECONDS = 6
PAGE_TIMEOUT_SECONDS = 6

USER_AGENT = "FluxAI/0.1"

DEFAULT_WEIGHT_AUTO = 1.15
DEFAULT_WEIGHT_MANUAL = 2.0

W2V_DIR = DATA_DIR / "word2vec"
